-- Baseline schema, hand-cleaned from `pg_dump --schema-only` of the Postgres
-- volume that Hibernate's ddl-auto=update built from the current entities.
--
-- Every statement is IF NOT EXISTS-safe (constraints inlined into CREATE
-- TABLE rather than Hibernate/pg_dump's separate ALTER TABLE ADD CONSTRAINT
-- form) so this migration is a no-op against a table that already exists.
-- That's required because spring.flyway.baseline-version=0 means Flyway
-- still runs V1 even on an already-populated compose volume -- baselining
-- at version 0 only records history, it doesn't skip migrations above it.
-- Table order follows FK dependencies (referenced table before referencer)
-- since the FKs below are inlined rather than added afterward.

CREATE TABLE IF NOT EXISTS users (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(255) NOT NULL UNIQUE,
    password_hash varchar(255) NOT NULL,
    first_name varchar(255),
    last_name varchar(255),
    role varchar(20) NOT NULL,
    created_at timestamp(6) without time zone
);

CREATE TABLE IF NOT EXISTS categories (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255) NOT NULL,
    slug varchar(255) UNIQUE,
    parent_id bigint REFERENCES categories(id),
    description varchar(255)
);

CREATE TABLE IF NOT EXISTS products (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name varchar(255),
    description varchar(255),
    price numeric(10,2) NOT NULL,
    sku varchar(255) UNIQUE,
    stock_quantity integer,
    category_id bigint REFERENCES categories(id),
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone
);

CREATE TABLE IF NOT EXISTS carts (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint UNIQUE REFERENCES users(id),
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone
);

CREATE TABLE IF NOT EXISTS addresses (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    street varchar(255),
    city varchar(255),
    state_or_province varchar(255),
    postal_code varchar(255),
    country varchar(255),
    user_id bigint NOT NULL REFERENCES users(id)
);

CREATE TABLE IF NOT EXISTS orders (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL REFERENCES users(id),
    order_number varchar(255) NOT NULL UNIQUE,
    status varchar(255) NOT NULL
        CHECK (status IN ('PENDING', 'PAID', 'SHIPPED', 'DELIVERED', 'CANCELLED')),
    shipping_street varchar(255),
    shipping_city varchar(255),
    shipping_state varchar(255),
    shipping_postal_code varchar(255),
    shipping_country varchar(255),
    subtotal numeric(10,2),
    tax numeric(10,2),
    shipping_cost numeric(10,2),
    total numeric(10,2) NOT NULL,
    created_at timestamp(6) without time zone,
    payment_reference varchar(255)
);

CREATE TABLE IF NOT EXISTS cart_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cart_id bigint NOT NULL REFERENCES carts(id),
    product_id bigint NOT NULL REFERENCES products(id),
    quantity integer NOT NULL,
    unit_price numeric(10,2)
);

CREATE TABLE IF NOT EXISTS order_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id bigint NOT NULL REFERENCES orders(id),
    product_id bigint REFERENCES products(id),
    product_name varchar(255) NOT NULL,
    quantity integer NOT NULL,
    unit_price numeric(10,2) NOT NULL,
    subtotal numeric(10,2) NOT NULL
);

CREATE TABLE IF NOT EXISTS order_number_seq (
    id bigint PRIMARY KEY,
    next_val bigint NOT NULL
);

-- Seed the singleton sequence row (moved from data.sql, which only runs
-- against embedded H2 in tests and never against Postgres). WHERE NOT
-- EXISTS keeps this safe to re-run and kills the first-order race on
-- fresh DBs by ensuring row id=1 always exists before nextOrderNumber().
INSERT INTO order_number_seq (id, next_val)
SELECT 1, 1
WHERE NOT EXISTS (SELECT 1 FROM order_number_seq WHERE id = 1);
